### ISSUE TITLE
My tool always hit : error HidD_SetOutputReport 50: The request is not supported.

### ISSUE THREAD

**Issue by hublin2** [microsoft/CFU#53]
GetVersion function is fine, but the Update furnction does not work.
Please help! thanks.
I am using the original VirtualDevice_MCU.offer.bin and VirtualDevice_MCU.payload.bin as my input files.

![image](https://user-images.githubusercontent.com/53160210/187477500-860081d5-505d-439c-98a2-dc6b4873ce4c.png)

**Comment by samtertzakian** [comment]
Hi Hub,
The issue is that the tool only uses HID_SetOutputReport(). But this option does not always work. The tool must be modified to support WriteFile(). Please see here: https://learn.microsoft.com/en-us/windows-hardware/drivers/hid/sending-hid-reports
Later we will modify the tool to support both options, or you submit a PR for it.

**Comment by hublin2** [comment]
Hi Sam,

Thank you, 
After using WriteFile instead of HidD_SetOutputReport, and adding one missing GENERIC_WRITE flag in the CreateFile handle for this out report, this tool works good here, wonderful.

Glad to have you and your team's strong help here.

Thanks again.

Hub
